=== Gotrufo-Eloy/Proyectos/Marcas/XSD/repasoHotel.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="hotel">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="room" minOccurs="2" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="roomNumber">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="roomType">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Individual"/>
                                        <xs:enumeration value="Doble"/>
                                        <xs:enumeration value="Suite"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="priceNight">
                                <xs:simpleType>
                                    <xs:restriction base="xs:float">
                                        <xs:minExclusive value ="0"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="huesped" minOccurs="2" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="idHuesped">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="HUESPED-\d{4}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="nombreHuesped">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="fechaEntrada">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{4}-\d{2}-\d{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="fechaSalida">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{4}-\d{2}-\d{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="roomNumber">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Gotrufo-Eloy/Proyectos/Marcas/XML/repasoHotel.xml
<?xml version="1.0" encoding="UTF-8"?>
<hotel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="C:\Users\falso\OneDrive\Documentos\Proyectos\Marcas\XSD\repasoHotel.xsd">

       <room>
              <roomNumber>123</roomNumber>
              <roomType>Individual</roomType>
              <priceNight>100</priceNight>
       </room>
       <room>
              <roomNumber>123</roomNumber>
              <roomType>Individual</roomType>
              <priceNight>100</priceNight>
       </room>
       
       <huesped>
              <idHuesped>HUESPED-1234</idHuesped>
              <nombreHuesped>EloyDelgado</nombreHuesped>
              <fechaEntrada>2024-10-10</fechaEntrada>
              <fechaSalida>2024-10-11</fechaSalida>
              <roomNumber>321</roomNumber>
       </huesped>
       <huesped>
              <idHuesped>HUESPED-1234</idHuesped>
              <nombreHuesped>EloyDelgado</nombreHuesped>
              <fechaEntrada>2024-10-10</fechaEntrada>
              <fechaSalida>2024-10-11</fechaSalida>
              <roomNumber>123</roomNumber>
       </huesped>
</hotel>
